spring:
    application:
        name: Gateway
eureka:
    client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka
server:
    port: 8888
security:
    basic:
        enable: false


zuul:
    host:
        socket-timeout-millis: 30000