logging:
    level:
        com.banashko.hotelsbookingmicroservice: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
spring:
    application:
        name: HotelsBookingMicroservice
    h2:
        console:
            enabled: true
            path: /h2-console

    datasource:
        url: jdbc:h2:mem:hotelsdb
        driverClassName: org.h2.Driver
        username: sa
        password:
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.H2Dialect
    jackson:
        serialization:
            fail-on-empty-beans: false
eureka:
    client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka
    instance:
            lease-renewal-interval-in-seconds: 15
            lease-expiration-duration-in-seconds: 70
server:
    port: 8081
security:
    basic:
        enable: false
